#!/bin/bash

function iYd() { clear
    while [ "$op_iYd" != 4 ]; do
        echo -e "\e[1;33m\033[1m*--------------------------------------*\e[0m"
        echo -e "\e[1;33m\033[1m|\e[0m 1. Cerrar procesos \e[1;32m[ NECESARIO PID ]\e[0m \e[1;33m\033[1m|\e[0m"
        echo -e "\e[1;33m\033[1m|\e[0m 2. Comprobar \e[1;32m[ PID ]\e[0m                        \e[1;33m\033[1m|\e[0m"
        echo -e "\e[1;33m\033[1m|\e[0m 3. Iniciar aplicaciones              \e[1;33m\033[1m|\e[0m"
        echo -e "\e[1;33m\033[1m|\e[0m 4. \033[0;101mVolver\033[0m                            \e[1;33m\033[1m|\e[0m"
        echo -e "\e[1;33m\033[1m*--------------------------------------*\e[0m"
        read -r -p "=> " op_iYd
        echo

        case $op_iYd in 
            1) sleep 1s
                echo "Para cerrar procesos sera necesario el numero PID el cual"
                echo "es el, Identificad de procesos (Process Indentifiers). "
                echo "Puedes abrir el administrador de tareas anterior y comprobar el PID"
                read -r -p "PID => " pid

                if [ "$pid" -le 1116 ]; then
                    echo -e "\e[1;35m\033[4mLa integridad del sistema se veria afectada\e[0m\033[0m"
                    #Algo a tener en cuenta es que todo los parámetros que están por debajo de 1116
                    #Son procesos que afectan directamente a la Terminal y el sistema, siendo así
                    #que los procesos 387, 792 y 1031 rompen el sistema.
                else
                    killall -u "$pid"
                    #La idea de usar [ killall ] es matar todo el árbol de proceso de dicha app.
                fi
                echo
            ;;

            2)
                echo
                top
                echo
                read -n1 -p "Presione cualquier tecla para [ CONTINUAR ]..." op_iYd
                [ "$op_iYd" = true ]
                clear
            ;;

            3)
                echo "Ingrese el nombre de la aplicacion la cual desea lanzar"
                read -r -p "Nombre => " ap
                ( exec "$ap" )
                echo
            
            ;;

            4)
                unset "$op_iYd"
                unset "$pid"
                unset "$ap"
                ( exec "./Script.sh" )
            ;;

            *)
                clear
                echo
                echo -e "\033[4;35mNo es una opcion lo que intentas\e[0m"
                echo
                sleep 2s
                clear
                [ "$op_iYd" = true ]
            ;;
        esac #Final del case 3
   done #Final del while 3
}

iYd
