#!/bin/bash

function user() { clear
    while [ "$op_user" != 3 ]; do
        echo -e "\e[0;33m\033[1m*---------------------------------------*\e[0m"
        echo -e "\e[0;33m\033[1m|\e[0m 1. Mostrar usuarios actuales          \e[0;33m\033[1m|\e[0m"
        echo -e "\e[0;33m\033[1m|\e[0m 2. Mostrar usuarios antes conectados  \e[0;33m\033[1m|\e[0m"
        echo -e "\e[0;33m\033[1m|\e[0m 3. \033[0;101m\033[1;97mVolver\033[0m                             \e[0;33m\033[1m|\e[0m"
        echo -e "\e[0;33m\033[1m*---------------------------------------*\e[0m"
        read -r -p "=> " op_user
        echo

        case $op_user in 
            1) sleep 1s
                w
                #Muestra los usuarios en el sistema
                read -n1 -p "Presione cualquier tecla para [ CONTINUAR ]..." op_user
                [ "$op_user" = true ]
                clear
            ;;

            2) sleep 1s
                last
                #Muestra todo los usuarios que iniciaron sesión por ultima vez 
                read -n1 -p "Presione cualquier tecla para [ CONTINUAR ]..." op_user
                [ "$op_user" = true ]
                echo
                clear
            ;;
            
            3)
                unset "$op_user" #[ unset ] borra la variable en memoria al salir de la funcion. 
                ( exec "./Script.sh" )
                #Con el comando [ exec ] reemplaza al Shell sin crear un nuevo proceso. 
                #Sin embargo, podemos ponerlo en una SubShell, la cual usara 
                #un porcentaje de procesador y ram, para usar esto es 
                #quitando el comando [ exec ] y dejando solo los paréntesis y el path del script:
                #[ ( "./Script.sh" ) ].
                #(La segunda opción es buena idea usarla en caso que se dese ejecutar tareas pesadas)
            ;;

            *)
                clear
                echo
                echo -e "\033[4;35mNo es una opcion lo que intentas\e[0m"
                echo
                sleep 2s
                clear
                [ "$op_user" = true ]

            ;;
        esac #Final del case 4
    done #Final del while 4
}

user